[book]
title = "KEDA 文件 - 繁體中文版"
authors = ["KEDA Community"]
description = "Kubernetes 事件驅動自動擴縮器 (KEDA) 繁體中文文件"
language = "zh-TW"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/kedacore/keda-docs"
